Feature/homework 2
VladPionerDevel/8-Ball-Without-Actual-Ball pull request #3
Opened 2022-02-20 19:28 UTC by VladPionerDevel

2022-02-21 17:12 UTC, AnnaSahaidak requested changes

2022-02-21 17:12 UTC, AnnaSahaidak commented on 8BallWithoutActualBall/ClassConfiguration.swift
>          //MARK: Initialise components.
Во-первых, MARK служат для разделения групп методов, свойств, а не кода в рамках метода, во-вторых тут пара строк и итак ясно что происходит, не нужно пояснять и так очевидный код

2022-02-21 17:12 UTC, AnnaSahaidak commented on 8BallWithoutActualBall/Modules/ShakePresenter.swift
> +    private var defaultValues: DefaultValues = UserDefaultsValues()
Это тоже можно инжектить, а не объявлять внутри. Например, может быть еще один провайдер дефолтных ответов, кроме UserDefaults.

2022-02-21 17:12 UTC, AnnaSahaidak commented on 8BallWithoutActualBall/SettingsViewController.swift
> +    private var defaultValues: DefaultValues = UserDefaultsValues()
Тоже самое, стоит инжектить

2022-02-21 17:12 UTC, AnnaSahaidak commented on 8BallWithoutActualBall/ShakeViewController.swift
> +    private var animationRoataion: CABasicAnimation = {
Не поняла зачем ты вынес это в переменную.

2022-02-21 17:12 UTC, AnnaSahaidak commented on 8BallWithoutActualBall/UserDefaultsValues.swift
> +protocol DefaultValues {
Неочевидный нейминг, я бы назвала DefaultAnswerProvider или что-то в этом духе

2022-02-21 17:12 UTC, AnnaSahaidak commented on 8BallWithoutActualBall/UserDefaultsValues.swift
> +    var answer: String {mutating get set}
после и перед фигурными скобками нужны пробелы
```suggestion
    var answer: String { mutating get set }
```

2022-02-21 17:12 UTC, AnnaSahaidak commented on 8BallWithoutActualBall/UserDefaultsValues.swift
> +struct UserDefaultsValues: DefaultValues {
Тут тоже, структура четко работает с дефолтными ответами, по названию это не ясно. Если бы тут была работа с любыми переменными, на дженериках, например, то да, название подходило бы.

2022-02-21 17:12 UTC, AnnaSahaidak commented on 8BallWithoutActualBall/ClassConfiguration.swift
>      class func shakeModule(configure viewController: ShakeDisplayLogic){
```suggestion
    class func shakeModule(configure viewController: ShakeDisplayLogic) {
```

2022-02-21 17:12 UTC, AnnaSahaidak commented on 8BallWithoutActualBall/Modules/ShakeInteractor.swift
> +    required init(answerWorker: AnswerWorker, presenter: ShakePresentationLogic?){
```suggestion
    required init(answerWorker: AnswerWorker, presenter: ShakePresentationLogic?) {
```

2022-02-21 17:12 UTC, AnnaSahaidak commented on 8BallWithoutActualBall/Modules/ShakePresenter.swift
> +    required init(viewController: ShakeDisplayLogic?){
```suggestion
    required init(viewController: ShakeDisplayLogic?) {
```

2022-02-21 17:12 UTC, AnnaSahaidak commented on 8BallWithoutActualBall/Modules/ShakePresenter.swift
>      func presentDefaultAnswers()  {
```suggestion
    func presentDefaultAnswers() {
```

2022-02-21 17:12 UTC, AnnaSahaidak commented on 8BallWithoutActualBall/Modules/ShakePresenter.swift
>              self.presentDefaultAnswers()
тут self не нужен

2022-02-21 17:12 UTC, AnnaSahaidak commented on 8BallWithoutActualBall/ShakeViewController.swift
>          ClassConfiguration.shakeModule(configure: self)
Добавь перенос после super.init(coder: coder)

2022-02-21 17:12 UTC, AnnaSahaidak commented on 8BallWithoutActualBall/ClassConfiguration.swift
>      class func shakeModule(configure viewController: ShakeDisplayLogic){
По поводу ClassConfiguration, его можно сделать структурой (не вижу причин делать классом) и функция shakeModule не обязательно должна быть static.

2022-02-23 09:53 UTC, VladPionerDevel commented on 8BallWithoutActualBall/ShakeViewController.swift
> +    private var animationRoataion: CABasicAnimation = {
я вынес это в переменную чтобы убрать из метода addAnimationRotaion двойную ответственность. Чтобы метод только добавлял анимацию а не создавала ее. единственное что это можно сделать не var а let

2022-02-23 12:09 UTC, AnnaSahaidak commented on 8BallWithoutActualBall/ShakeViewController.swift
> +    private var animationRoataion: CABasicAnimation = {
Смотри, ты слишком буквально понял этот принцип). Тут нет двойной ответственности, в одном методе нормально создавать и добавлять анимацию, это и есть ответственность этого метода добавить анимацию, просто чтоб добавить анимацию нужно создать.

2022-02-23 18:00 UTC, AnnaSahaidak approved these changes
Есть еще комментарии, нужно `AnswerWorker` тоже закрыть протоколом, он уже есть.
Остальное желательно тоже пофиксить (особенно приведение к типу), но можно и в следующем дз если сейчас совсем нет времени.

2022-02-23 18:00 UTC, AnnaSahaidak commented on 8BallWithoutActualBall/ClassConfiguration.swift
> +        let presenter = ShakePresenter(viewController: viewController, defaultValues: DefaultValues() as DefaultAnswerProvider)
Приведение типа лишнее, т.к. DefaultValues конфермит протокол DefaultAnswerProvider, компилятор это поймет.

2022-02-23 18:00 UTC, AnnaSahaidak commented on 8BallWithoutActualBall/Modules/ShakePresenter.swift
> +    var defaultValues: DefaultAnswerProvider
Должна быть let, т.к. переменная инициализируются в ините и не должна меняться. А еще ее стоит сделать private (но это уже больше к третьему дз относится)

2022-02-23 18:00 UTC, AnnaSahaidak commented on 8BallWithoutActualBall/SettingsViewController.swift
> +    var defaultValues: DefaultAnswerProvider
Должна быть let, т.к. переменная инициализируются в ините и не должна меняться. А еще ее стоит сделать private (но это уже больше к третьему дз относится)

2022-02-23 18:00 UTC, AnnaSahaidak commented on 8BallWithoutActualBall/ShakeViewController.swift
> +            return SettingsViewController(coder: coder, defaultValues: DefaultValues() as DefaultAnswerProvider)
Тут тоже не нужно приводить к типу DefaultAnswerProvider

2022-02-23 18:03 UTC, AnnaSahaidak commented on 8BallWithoutActualBall/Modules/ShakeInteractor.swift
>      private let worker: AnswerWorker
А у тебя ж был протокол `AnswerGetting`, нужно тут протокол использовать

2022-02-24 11:21 UTC, merged